name: MLflow Project CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI     : https://dagshub.com/richardlois1/SML_Modelling.mlflow/
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Update conda and configure channels
      run: |
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update -n base -c defaults conda

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mlfow-env
        environment-file: MLProject/conda.yaml
        python-version: 3.10.*

    - name: Install MLflow CLI
      shell: bash -l {0}
      run: |
        pip install mlflow==2.12.2

    - name: Run MLflow Project
      shell: bash -l {0}
      working-directory: MLProject
      run: |
        mlflow run . -P data_path=mobile_price_classification_preprocessing.csv

    # - name: Upload model artifact
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: mobile-price-class-model
    #     path: MLProject/mlruns/

    - name: Download latest model artifact from DagsHub
      shell: bash -l {0}
      working-directory: MLProject
      run: |
        python download_model.py

    - name: Generate Dockerfile 
      shell: bash -l {0}
      working-directory: MLProject
      run: |
        mlflow models generate-dockerfile -m downloaded_model/model

    - name: Patch Dockerfile to use python3.10
      working-directory: MLProject/downloaded_model/model
      run: |
        sed -i 's/python3.8/python3.10/g' Dockerfile
        sed -i 's/python3.8-distutils/python3.10-distutils/g' Dockerfile
        sed -i 's/python \/tmp\/get-pip.py/python3.10 \/tmp\/get-pip.py/g' Dockerfile

    - name: Build Docker image
      working-directory: MLProject
      run: |
        docker build -t random-forest-model:latest -f downloaded_model/model/Dockerfile downloaded_model/model

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag random-forest-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/random-forest-model:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/random-forest-model:latest
